version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
  nlp:
    build: ./packages/nlp
    ports:
      - "9002:9001"
    environment:
      - NLP_PORT=9001
  api:
    build: ./packages/api
    depends_on:
      - postgres
      - redis
      - minio
      - nlp
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: appdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET: deliveryapp
      NLP_URL: http://nlp:9001
      WA_VERIFICATION_NUMBER: 923001112223
      WA_MESSAGE_TEMPLATE: "Verify code: {{CODE}}"
      WA_CODE_TTL_SECONDS: 300
      API_PORT: 8080
    ports:
      - "8080:8080"
  web:
    build: ./packages/web
    depends_on:
      - api
    environment:
      VITE_API_URL: http://localhost:8080
    ports:
      - "5173:80"
volumes:
  db-data:
  minio-data:
