version: '3.9'
services:
  db:
    image: postgres:16
    container_name: deliveryapp-db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: deliveryapp-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    container_name: deliveryapp-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console UI
    volumes:
      - minio_data:/data

volumes:
  db_data: {}
  minio_data: {}

