-- CreateEnum
CREATE TYPE "Role" AS ENUM ('CUSTOMER','MERCHANT','ADMIN');
CREATE TYPE "ReqStatus" AS ENUM ('PENDING','ACCEPTED','DISPATCHED','DELIVERED','CANCELED');
CREATE TYPE "OfferStatus" AS ENUM ('PASSED','ACCEPTED');

-- CreateTable
CREATE TABLE "User" (
  "id" TEXT PRIMARY KEY,
  "phone" TEXT NOT NULL UNIQUE,
  "name" TEXT,
  "role" "Role" NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'active',
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "updatedAt" TIMESTAMP DEFAULT NOW()
);

CREATE TABLE "Address" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL,
  "line" TEXT NOT NULL,
  "city" TEXT NOT NULL,
  "lat" DOUBLE PRECISION NOT NULL,
  "lng" DOUBLE PRECISION NOT NULL,
  "createdAt" TIMESTAMP DEFAULT NOW(),
  CONSTRAINT "Address_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE "Merchant" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL UNIQUE,
  "shopName" TEXT NOT NULL,
  "isOpen" BOOLEAN NOT NULL DEFAULT TRUE,
  "minOrder" INTEGER NOT NULL DEFAULT 0,
  "radiusKm" INTEGER NOT NULL DEFAULT 5,
  "ratingAvg" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "ratingCount" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP DEFAULT NOW(),
  CONSTRAINT "Merchant_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE "Request" (
  "id" TEXT PRIMARY KEY,
  "customerId" TEXT NOT NULL,
  "addressId" TEXT NOT NULL,
  "itemsJson" JSONB NOT NULL,
  "note" TEXT,
  "status" "ReqStatus" NOT NULL DEFAULT 'PENDING',
  "etaMinutes" INTEGER,
  "serviceFeePc" INTEGER NOT NULL DEFAULT 5,
  "createdAt" TIMESTAMP DEFAULT NOW(),
  "acceptedAt" TIMESTAMP,
  CONSTRAINT "Request_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "Request_addressId_fkey" FOREIGN KEY ("addressId") REFERENCES "Address"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE "Offer" (
  "id" TEXT PRIMARY KEY,
  "requestId" TEXT NOT NULL,
  "merchantId" TEXT NOT NULL,
  "fee" INTEGER NOT NULL,
  "minutes" INTEGER NOT NULL,
  "status" "OfferStatus" NOT NULL DEFAULT 'PASSED',
  "createdAt" TIMESTAMP DEFAULT NOW(),
  CONSTRAINT "Offer_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "Request"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "Offer_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "Merchant"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE "Rating" (
  "id" TEXT PRIMARY KEY,
  "requestId" TEXT NOT NULL UNIQUE,
  "customerId" TEXT NOT NULL,
  "merchantId" TEXT NOT NULL,
  "stars" INTEGER NOT NULL,
  "comment" TEXT,
  "createdAt" TIMESTAMP DEFAULT NOW(),
  CONSTRAINT "Rating_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "Request"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
